# MPP Chat Client Configuration
# -----------------------------

# The IP address or hostname of the server
chat.server.host=127.0.0.1

# The port number the server is listening on
chat.server.port=55556