# MPP Chat Client Configuration
# -----------------------------

# The IP address or hostname of the server
chat.server.host=localhost

# The port number the server is listening on
chat.server.port=55556